### PR TITLE
Classic: Feature: Tooltip: Added feature for alt key showing full stack price.

### PR DESCRIPTION
**Pull request by FuSoYa**
Added feature and config for holding alt key to show full stack price.

Only implemented config text for enUS locale.

### CODE REVIEW

**Comment by plusmouse** [comment]
Why do you want Alt to show the stack price, when Shift already does that?

**Comment by plusmouse** [comment]
If the behaviour is the same for Alt and Shift I'd prefer the option to be a dropdown to select the preferred behaviour, rather than multiple checkboxes in the settings.

**Comment by FuSoYa** [comment]
I don't know if there is a better way you want to implement the config for this but the feature isn't exactly the same as holding shift. Shift shows the price of the AH for that stack, so if you have x3 of the item is will go from showing x1 to x3. I found myself wanting to know what a full stack sells for. So when you hold alt it uses itemInfo to find out what a full stack is allowed by game, and then gives you the price of that, lets say x20.

**Comment by plusmouse** [comment]
Ok. That looks good. I've merged and added in the option for retail too.

**Comment by plusmouse** [comment]
On review the feature is too niche to include in Auctionator. This mini-addon will add similar functionality:
image

[FullStackPrices-6cf939b-wrath.zip](https://github.com/Auctionator/Auctionator/files/12232331/FullStackPrices-6cf939b-wrath.zip)

**Comment by FuSoYa** [comment]
@plusmouse well I was excited that I finally contributed to something then now I am saddened it was removed. It's your project though and can do whatever. Thanks for at least taking a look at it.

**Pull request merged**
