### PR TITLE
Classic: Compute shopping list search total based on entry quantities

### LINKED ISSUE #1401: Shopping list feature request: show total gold required for each/selected list
Hello,

First of all, just wanted to thank you for amazing new shopping list rework.
You have no idea just how much easier and more useful it is now. Wow!

Minor improvement i'd like to propose is to show total gold required to buy all materials for each shopping list. (or at least, for currently selected one, once all materials are loaded).
This would be extremely valuable mainly for purpose of waiting for a good deal.
One week your shopping list might cost 1k, next week 5k, all depending on material cost at the time.
I believe this should be relatively simple, now that quantity feature has been added :)
Lists without quantity set for each item, will not have this total shown.

Example of where that total could be located:
image

### PR DESCRIPTION
**Pull request by abeeler**
fixes #1401

### CODE REVIEW

**Comment by abeeler** [comment]
Example List:
ExampleList

And example of that list's results when using the search list button:
ExampleResults

**Comment by abeeler** [comment]
Implementation of the list computation is done on the flavor-agnostic MultiSearchMixin file but option configuration is only on the ShoppingAlt window which seems to be Classic-only. I've only been playing on Classic so didn't want to implement across the board without someone else testing on retail.

Possible improvements are to set a default icon to a dollar sign or something similar but I'm fairly new to addon coding so don't know where the best place to look for potential images would be.

**Comment by plusmouse** [comment]
Would there be any benefit to using this over the embedded craft costs in the crafting panels? They also update when a search is done.
image

**Comment by abeeler** [comment]
My example above was probably not the best as that list was what I was using to track the costs of crafting the final product to determine if buying the recipe was worth it or not. For known recipes the only benefit of this feature would be if you wanted to check nested recipe material costs to get the most profitable combination of purchases. E.g. for your lesser healing potion you could have a list that included the reagents for minor healing potion directly:

- Peacebloom [x1]
- Silverleaf [x1]
- Briarthorn [x1]

Otherwise the implementation of this feature was more focused on the original request in #1401 which seemed tailored for commonly used items that needed to be replenished and not for crafting recipes.

**Pull request closed without merging**
