### PR TITLE
Added API to create Shopping Lists

### PR DESCRIPTION
**Pull request by derfloh205**

### CODE REVIEW

**Comment by plusmouse** [comment]
Before this can be merged, for `GetShoppingListItemString` there's an internal API that converts a table to the appropriate search string:
```lua
Auctionator.Search.ReconstituteAdvancedSearch(term)
```
so
```lua
local searchString = Auctionator.Search.ReconstituteAdvancedSearch({
  searchString = "Serevite Ore", isExact = true, tier = 3, quantity = 3
})
```
would create a search term for Serevite Ore, gold quality and for purchasing just 3.

Valid fields are:
```lua
    searchString,
    isExact,
    categoryKey,
    minLevel,
    maxLevel,
    minPrice,
    maxPrice,
    minItemLevel,
    maxItemLevel,
    minCraftedLevel,
    maxCraftedLevel,
    quality, --regular quality
    tier = tier, -- dragonflight crafted reagent quality
    expansion,
    quantity,
 ```

**Comment by plusmouse** [comment]
Have you tried using the https://github.com/Auctionator/Auctionator/wiki/API-Documentation#advanced-search-terms API and checked whether it would meet your needs?

**Comment by derfloh205** [comment]
I will take a look :)

**Comment by derfloh205** [comment]
> Have you tried using the https://github.com/Auctionator/Auctionator/wiki/API-Documentation#advanced-search-terms API and checked whether it would meet your needs?

I tried to test this with the following snippet but always get this error, could it be that there are other required fields I do not have included?
image

**Comment by plusmouse** [comment]
Yep, there's a field missing in the earlier example, add
```
categoryKey = "",
```
to the search term
image

**Comment by derfloh205** [comment]
@plusmouse Pushed a new commit updating the API
This also includes an api call to test the apis

**Pull request merged**
