### PR TITLE
Update Main.xml

### PR DESCRIPTION
**Pull request by cleanlock**
Added name to StartScan Button, so it can be accessed and re-colored.

Would highly appreciate a merge.

### CODE REVIEW

**Comment by plusmouse** [comment]
I don't see any point to this change, as it already has a `parentKey` which means it can be accessed for theming.

**Comment by cleanlock** [comment]
well, I tried to get it with ```:GetRegions()```, and I was unable to access it as it is behind UserData.

**Comment by plusmouse** [comment]
image

**Comment by plusmouse** [comment]
Ah, I was looking at the wrong button

**Comment by cleanlock** [comment]
Tyvm!

**Pull request closed without merging**
