### PR TITLE
Use LibUIDropDownMenu

### PR DESCRIPTION
**Pull request by mbattersby**
Example for embedding and using LibUIDropDownMenu as mentioned in #1133.

No need to be careful of my feelings, feel free to close it unmerged. It's really just a suggestion and something for you to look at if you feel like it.

### CODE REVIEW

**Comment by mbattersby** [comment]
Note that this is barely tested on retail and completely untested on classic and BCC.

**Comment by mbattersby** [comment]
I also didn't try this with the packager, so it may not package correctly.

**Comment by plusmouse** [comment]
I've opened and tested the code. There is one glitch, second level dropdowns don't close the first level when the second level is clicked. There's a few dropdowns with second (or third) levels that this impacts. It looks like a library issue so I've opened an issue https://www.wowace.com/projects/libuidropdownmenu/issues/12
image

Also, was there a specific usecase that triggered the taint?

**Comment by mbattersby** [comment]
I can't pin it exactly to Auctionator, but the trigger was an infinity of "Attempt to access fprbidden object from code tainted by addon" errors fighting LFR Prototype Pantheon at the same time the taintlog is spewing out hundreds of
```
3/26 11:48:06.316  An action was blocked in combat because of taint from Auctionator - CompactRaidGroup1:unusedFunc()
3/26 11:48:06.316      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:160 CompactRaidFrameContainer_LayoutFrames()
3/26 11:48:06.316      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130 CompactRaidFrameContainer_TryUpdate()
3/26 11:48:06.316      Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57 CompactRaidFrameContainer_OnEvent()
3/26 11:48:06.316      CompactRaidFrameContainer:OnEvent()
```

I think it's triggered by the friendly nameplates on the seed adds that need healing (IIRC some nameplate stuff actually a CUF).

It's not a very repeatable case, so I can't really do any binary testing. Obviously Auctionator is pretty early alphabetically, but then it's definitely tainting things that LibUIDropDownMenu would stop. E.g.,

```
3/26 11:36:52.156  Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by Auctionator - Interface\SharedXML\UIDropDownMenu.lua:37
3/26 11:36:52.156      securecall()
3/26 11:36:52.156      Interface\SharedXML\UIDropDownMenu.lua:73 UIDropDownMenu_Initialize()
3/26 11:36:52.156      Interface\AddOns\Auctionator\Source\Components\Mixins\DropDown.lua:48 <unnamed>:Initialize()
3/26 11:36:52.156      Interface\AddOns\Auctionator\Source\Components\Mixins\DropDown.lua:30 <unnamed>:InitAgain()
3/26 11:36:52.156      Interface\AddOns\Auctionator\Source\Components\Mixins\DropDown.lua:18
3/26 11:36:52.156      CreateFrame()
3/26 11:36:52.156      Interface\AddOns\Auctionator\Source\Config\InitializeFrames.lua:3 InternalInitializeFrames()
3/26 11:36:52.156      Interface\AddOns\Auctionator\Source_Mainline\Config\InitializeFrames.lua:2 InitializeFrames()
3/26 11:36:52.156      Interface\AddOns\Auctionator\Source\Variables\Main.lua:9 Initialize()
3/26 11:36:52.156      Interface\AddOns\Auctionator\Source\Events\VariablesLoaded.lua:4 VariablesLoaded()
3/26 11:36:52.156      Interface\AddOns\Auctionator\Source\Events\Handler.lua:7 Handler()
3/26 11:36:52.156      AuctionatorCore:OnEvent()
```

**Comment by mbattersby** [comment]
I think I will have this multi-level closing problem in my own addons too, so I'll keep an eye out in case I notice the fix.

**Comment by mbattersby** [comment]
FWIW "Attempt to access forbidden object from code tainted by addon" is something I've never seen before, that's why I suspect the new CUF changes have even more awful taint problems with dropdowns.

**Comment by plusmouse** [comment]
The taint error from the dropdowns wouldn't show unless a dropdown was triggered. Did you attempt to access a dropdown, or was it meant to show one at somepoint?

Looking at the UI code it seems the taint is triggered by the code trying to hide some frames, I'd guess they're secure frames from the error.

**Comment by mbattersby** [comment]
No, it does. Doesn't require using the dropdown, never has. The CUF dropdown taint problems are awful.

**Comment by plusmouse** [comment]
I don't want to add the second level UI glitch with the dropdowns - it made the UI feel unresponsive.

The TaintLess solved an issue where a guild master couldn't use the right-click menu to promote a character in their guild - fortunately that was reproducible so I was able to verify the fix worked.

**Comment by mbattersby** [comment]
Yeah the UI glitch is no good, definitely.

Thanks for the discussion, I'll close this off. I can't give you a reproduceable failure, and I understand that's too little for you to go on. Best wishes.

**Comment by plusmouse** [comment]
Update: Found that the reason the second levels weren't closing was because ` lib:CloseDropDownMenus()` wasn't being used; it had been left with `CloseDropDownMenus` and `HideDropDownMenu`.

**Comment by plusmouse** [comment]
As we're going to have to embed a library one way or another because of the taint I've embedded LibUIDropDown instead of TaintLess using your version with the fix for closing submenus.

**Comment by plusmouse** [comment]
Thanks for the pull request 😄

**Comment by mbattersby** [comment]
Sorry about the bad PR, and thanks for the update.

**Pull request closed without merging**
