### PR TITLE
Testing optional quantities to prepopulated for buying commodities on retail

### PR DESCRIPTION
**Pull request by plusmouse**
From this:
image
to this: (after clicking the Search button)
image
with the 12 set to the quantity automatically
image
And the option in the extended search parameters to set your own quantities
image

### CODE REVIEW

**Comment by plusmouse** [comment]
@Rezy942 You might be interested in trying out this preview release, see the above comment for what it includes (quantities in Shopping lists)
[Auctionator-10.1.5-3-ge58b4f8.zip](https://github.com/Auctionator/Auctionator/files/11637470/Auctionator-10.1.5-3-ge58b4f8.zip)

**Comment by plusmouse** [comment]
Also, combines quantities for tracked recipes:
image
image

**Comment by Rezy942** [comment]
Im away on vacation at the moment and wont be back for like 2-3 weeks :(. I can definetely test it out then if still needed but I believe in you! Looks amazing <33

**Comment by nanjuekaien1** [comment]
Forget localization
本地化
本地化 2

**Comment by plusmouse** [comment]
@nanjuekaien1 Fixed

**Pull request merged**
